android.useAndroidX=false
android.enableJetifier=false
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
org.gradle.jvmargs=-Xmx1536m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.workers.max=8
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
